### ISSUE TITLE
Team chat

### ISSUE THREAD

**Issue by cowlingj** [cowlingj/ludumdare-08-2018#2]

**Comment by AlexLarumbe** [comment]
Hey guys. Something came up and I won't be able to make it tomorrow, but I'll try to finish some of the sounds tonight and upload them.

**Comment by Destrark** [comment]
Well, that's the background added. I'll make a level 5 and is there anything else you want me to do afterwards?

**Comment by Destrark** [comment]
Added a level 5. That last section at the bottom is designed to trick the player by having the camera limit above the walkway leading to a point you can shoot the last breakable object. Put an enemy on the walkway above the last object. They will shoot the path in front of the walkway and the enemy will fall and appear to die but instead land on the walkway the player has to jump down to.
